# https://github.com/codecov/example-php
# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  include:
    - php: 5.4
      env: dependencies=lowest
  allow_failures:
    - php: nightly
  fast_finish: true


# Appended for Codecov.io
#before_install:
  #- sudo pip install codecov #slows down performance
  #- pip install --user codecov

# Commands to be run before your environment runs.
before_script:
  - travis_retry composer self-update
  #- if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then travis_retry composer require satooshi/php-coveralls:dev-master -n ; fi
  #- if [[ $TRAVIS_PHP_VERSION != '5.6' ]]; then travis_retry composer install --no-interaction --prefer-source ; fi
  - travis_retry composer install --no-interaction --prefer-source

# Commands you want to run that will verify your build.
script:
  #- vendor/bin/phpunit --coverage-clover=clover.xml
  - vendor/bin/phpunit -c phpunit.xml.dist

# Appended for Coveralls.io
#after_script:
  #- if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then php vendor/bin/coveralls -v --exclude-no-stmt ; fi

# Appended for Codecov.io
after_success:
  #- if [[ $(phpenv version-name) == '5.5' ]]; then bash <(curl -s https://codecov.io/bash) ; fi
  #- if [[ $TRAVIS_PHP_VERSION == '5.5' ]]; then bash <(curl -s https://codecov.io/bash) ; fi
  #- if [[ $TRAVIS_PHP_VERSION == '5.5' ]]; then bash -c "$(git log -1 --pretty=%B | tail -1)" ; fi
  #- if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then bash <(curl -s https://codecov.io/bash); fi
  - bash <(curl -s https://codecov.io/bash)

# Customize when the notification emails are sent.
notifications:
  email:
    recipients:
      #- albert_park@hotmail.com
      - albert@park.ac
  on_success: change
  on_failure: always

