# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

#install: true

# Appended for Codecov.io
before_install:
  #- pip install --user codecov
  - sudo pip install codecov

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  #- travis_retry composer self-update
  #- travis_retry composer install --no-interaction --prefer-source --dev

# Commands you want to run that will verify your build.
script:
  #- phpunit
  - vendor/bin/phpunit --coverage-clover=coverage.xml

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.6
    - php: 7.0
    - php: nightly
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
  email:
    recipients:
      #- albert_park@hotmail.com
      - albert@park.ac
  on_success: change
  on_failure: always

# Appended for Codecov.io
after_success:
  #- bash <(curl -s https://codecov.io/bash)
  #- codecov
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then codecov; fi
