# https://github.com/codecov/example-php


dist: trusty

# Required to run your project under the correct environment.
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

# Versions of PHP you want your project run with
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  include:
    - php: 5.3
      env: dependencies=lowest
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: nightly
  fast_finish: true


# Appended for Codecov.io
#before_install:
  #- sudo pip install codecov #slows down performance
  #- pip install --user codecov

# Commands to be run before your environment runs.
before_script:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction --prefer-source

# Commands you want to run that will verify your build.
script:
  - mkdir -p build/logs
  #- php -n php-cs-fixer.phar fix -v --dry-run --level=all src
  - output=$(php -n php-cs-fixer.phar fix -v --dry-run --level=all src); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
  - php ./vendor/bin/phpcs --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=build/config/phpcs.xml --ignore=*.html.php,*.config.php,*.twig.php src
  - php ./vendor/bin/phpmd src xml build/config/phpmd.xml --reportfile build/logs/pmd.xml
  - cp ~/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - php ./vendor/bin/phpunit -c phpunit.xml.dist
  - rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini


# Appended for Codecov.io
after_success:
  - curl -s https://gist.github.com/albertpark/985d39b759f356cdbbeb/raw > travis/ColorCLI.php
  - curl -s https://gist.github.com/albertpark/4551957f2332def300f3/raw > travis/junit.php
  - curl -s https://gist.github.com/albertpark/f68a8e2def7e37ea6bc3/raw > travis/pmd.php
  - curl -s https://gist.github.com/albertpark/ef9ed4553192ecd5ea44/raw > travis/checkstyle.php
  - php ./travis/checkstyle.php
  - php ./travis/pmd.php
  - php ./travis/junit.php

# Appended for Coveralls.io
#after_script:
  #- if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then php vendor/bin/coveralls -v --exclude-no-stmt ; fi
  #- bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://codecov.io/bash) -X coveragepy || echo "Codecov did not collect coverage reports"

# Customize when the notification emails are sent.
notifications:
  email:
    recipients:
      - albert@park.ac
  on_success: change
  on_failure: always
